# -*- coding: utf-8 -*-
"""Adding_fabric_patten_type_attributes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqySZpp7ZK88Zc8486U6QJiygelKFA87
"""

import pandas as pd

top = pd.read_csv('/content/drive/MyDrive/17k_csv/filtered_top_wear.csv')
top

"""# Adding Fabric Type and Pattern Type

Adding these column to other available attributes are useful to get warmth and breathability scores for getting weather suitability(sunny, rainy, snowy, cloudy) for each clothing item

Fabric annotation and Pattern annotation text files are available in dataset
"""

# Load the pattern annotation txt file
txt_path = "/content/drive/MyDrive/texture/fabric_ann.txt"
with open(txt_path, "r") as file:
    pattern_lines = file.readlines()

# Define the annotation dictionary
fabric_dict = {
    '0': 'denim',
    '1': 'cotton',
    '2': 'leather',
    '3': 'furry',
    '4': 'knitted',
    '5': 'chiffon',
    '6': 'other',
    '7': 'NA'
}

fabric_annotations = {}
for line in pattern_lines:
    parts = line.strip().split()
    if len(parts) == 4:
        img_name, _, upper_fabric, _ = parts
        fabric_type = fabric_dict.get(upper_fabric, 'NA')
        fabric_annotations[img_name] = fabric_type

# Map the annotations to the dataframe
top["Fabric_Type"] = top["Image_ID"].apply(lambda x: fabric_annotations.get(x, 'NA'))

# Load the pattern annotation txt file
txt_path = "/content/drive/MyDrive/texture/pattern_ann.txt"
with open(txt_path, "r") as file:
    pattern_lines = file.readlines()

# Define the annotation dictionary
pattern_dict = {
    0: 'floral',
    1: 'graphic',
    2: 'striped',
    3: 'pure color',
    4: 'lattice',
    5: 'other',
    6: 'color block',
    7: 'NA'
}

pattern_annotations = {}
lower_pattern_dict = {}
for line in pattern_lines:
    parts = line.strip().split()
    if len(parts) == 4:
        img_name, _, upper_pattern, _ = parts
        pattern_type = pattern_dict.get(int(upper_pattern), 'NA')
        pattern_annotations[img_name] = pattern_type

# Map the annotations to the dataframe
top["Pattern_Type"] = top["Image_ID"].apply(lambda x: pattern_annotations.get(x, 'NA'))